[package]
name = "uniswapv4-challenge-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
hex = "0.4"
num_cpus = "1.13.0"
rand = "0.8"
clap = { version = "4.0.0", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
